name: 'Deploy: issue_comment filter'
description: 'Triggers deployments via issue comment'
inputs:
  TOKEN:
    description: 'The GITHUB_TOKEN secret'
  ENVIRONMENTS:
    description: 'Environment names, comma separated'
outputs:
  DEPLOYMENT_ID:
    description: 'Created deployment id, may be empty'
  ENVIRONMENT:
    description: 'Environment being deployed to'
  DEPLOY_REF:
    description: 'Ref/branch being deployed'
  DEPLOY_ARGUMENTS:
    description: 'Extra arguments passed to deploy command'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: comment-deploy
